# Generated by Django 3.2 on 2022-03-24 07:54

import clients.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', clients.models.ClientManager()),
            ],
        ),
    ]
