# Generated by Django 3.2 on 2022-03-24 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to', to=settings.AUTH_USER_MODEL)),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
