# Generated by Django 3.2 on 2022-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=12, max_digits=8),
            preserve_default=False,
            null=True,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=13, max_digits=9),
            preserve_default=False,
            null=True,
        ),
    ]
